// src/components/ShareButton/ShareModal.tsx
import React, { useCallback } from 'react';
import { Check, Users } from 'lucide-react';
import { Modal } from '../Modal';
import { getSharedState, joinSession } from '../../utils/collaboration';
import { useDispatch } from 'react-redux';
import { setConnectionStatus, syncState } from '../../store/magazineSlice';
import { updateSettings } from '../../store/settingsSlice';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  onShare: () => void;
  allowEdit: boolean;
  onAllowEditChange: (allow: boolean) => void;
  copied: boolean;
  connectedUsers: number;
}

export function ShareModal({
  isOpen,
  onClose,
  onShare,
  allowEdit,
  onAllowEditChange,
  copied,
  connectedUsers
}: ShareModalProps) {
  const dispatch = useDispatch();

  const handleShareClick = useCallback(async () => {
    if (allowEdit) {
      try {
        const shareId = 'some-share-id'; // Replace with actual share ID logic
        const sharedState = await getSharedState(shareId);
        if (!sharedState) {
          throw new Error('Share not found or expired');
        }

        dispatch(setConnectionStatus(true));
        await joinSession(shareId);

        dispatch(syncState({
          magazine: {
            ...sharedState.magazine,
            isShared: true,
            allowEdit: true
          }
        }));

        dispatch(updateSettings(sharedState.settings));
      } catch (err) {
        console.error('Error connecting to session:', err);
        dispatch(setConnectionStatus(false));
      }
    }
    onShare();
  }, [allowEdit, dispatch, onShare]);

  return (
    <Modal isOpen={isOpen} onClose={onClose}>
      <div className="space-y-6">
        <div>
          <h3 className="text-lg font-medium text-gray-900">Share Layout</h3>
          <p className="mt-1 text-sm text-gray-500">
            Choose how you want to share your magazine layout
          </p>
        </div>

        {connectedUsers > 1 && (
          <div className="bg-blue-50 p-4 rounded-md">
            <div className="flex items-center text-sm text-blue-700">
              <Users className="w-4 h-4 mr-2" />
              {connectedUsers} users currently connected
            </div>
          </div>
        )}

        <div className="space-y-4">
          <label className="flex items-center space-x-3">
            <input
              type="checkbox"
              checked={allowEdit}
              onChange={(e) => onAllowEditChange(e.target.checked)}
              className="h-4 w-4 text-blue-600 rounded border-gray-300"
            />
            <span className="text-sm text-gray-700">Allow editing</span>
          </label>

          {allowEdit && (
            <div className="bg-blue-50 p-4 rounded-md">
              <div className="flex items-center text-sm text-blue-700">
                <Users className="w-4 h-4 mr-2 flex-shrink-0" />
                Recipients will be able to edit and collaborate on the layout
              </div>
            </div>
          )}
        </div>

        <div className="flex justify-end space-x-3">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 rounded-md"
          >
            Cancel
          </button>
          <button
            onClick={handleShareClick}
            className="inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-md"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 mr-2" />
                Copied!
              </>
            ) : (
              'Copy Share Link'
            )}
          </button>
        </div>
      </div>
    </Modal>
  );
}

// src/components/Share/ShareModal.vue
<script setup lang="ts">
import { computed } from 'vue';
import { X, Copy, Check, Users } from 'lucide-vue-next';

const props = defineProps<{
  isOpen: boolean;
  allowEdit: boolean;
  copied: boolean;
  connectedUsers: number;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'share'): void;
  (e: 'allowEditChange', value: boolean): void;
}>();

const handleAllowEditChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  emit('allowEditChange', target.checked);
};

const modalClass = computed(() => {
  return props.isOpen
    ? 'fixed inset-0 z-50 flex items-center justify-center bg-black/50'
    : 'hidden';
});
</script>

<template>
  <div :class="modalClass">
    <div class="w-full max-w-md p-6 mx-auto bg-white rounded-lg shadow-xl">
      <div class="flex items-center justify-between mb-4">
        <h2 class="text-xl font-semibold">Share</h2>
        <button
          @click="emit('close')"
          class="p-1 text-gray-500 rounded-full hover:bg-gray-100"
        >
          <X class="w-5 h-5" />
        </button>
      </div>

      <div class="mb-4">
        <div class="flex items-center mb-2">
          <Users class="w-4 h-4 mr-2 text-gray-500" />
          <span class="text-sm text-gray-500">{{ connectedUsers }} connected</span>
        </div>

        <div class="flex items-center">
          <input
            type="checkbox"
            id="allowEdit"
            :checked="allowEdit"
            @change="handleAllowEditChange"
            class="w-4 h-4 mr-2 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
          />
          <label for="allowEdit" class="text-sm text-gray-700">
            Allow editing
          </label>
        </div>
      </div>

      <div class="flex justify-end space-x-2">
        <button
          @click="emit('close')"
          class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
        >
          Cancel
        </button>
        <button
          @click="emit('share')"
          class="inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700"
        >
          <template v-if="copied">
            <Check class="w-4 h-4 mr-2" />
            Copied!
          </template>
          <template v-else>
            <Copy class="w-4 h-4 mr-2" />
            Copy link
          </template>
        </button>
      </div>
    </div>
  </div>
</template>
