// src/components/ArticleForm/index.tsx
import React, { useState, useEffect } from 'react';
import { useSelector } from 'react-redux';
import { PlusCircle, Wand2, Trash2 } from 'lucide-react';
import { Dropdown } from '../Dropdown';
import type { Article, Visual, LineHeight, Tag } from '../../types';
import { generateRandomArticle } from '../../utils/articleGenerator'; 
import { calculateWordsPerPage, calculateRequiredPages, ratioToPercent } from '../../utils/calculations';
import { BasicInfo } from './BasicInfo';
import { ContentLength } from './ContentLength';
import { Visuals } from './Visuals';
import type { RootState } from '../../store/store';

interface ArticleFormProps {
  onAdd: (article: Omit<Article, 'id' | 'startPage'>) => void;
  onDelete?: (id: string) => void;
  article?: Article | null;
}

export function ArticleForm({ onAdd, onDelete, article }: ArticleFormProps) {
  const availableTags = useSelector((state: RootState) => state.tags.tags);
  const [title, setTitle] = useState(article?.title || '');
  const [url, setUrl] = useState(article?.url || '');
  const [tags, setTags] = useState<Tag[]>(article?.tags || []);
  const [wordCount, setWordCount] = useState(article?.wordCount.toString() || '');
  const [pageCount, setPageCount] = useState(article?.pageCount.toString() || '1');
  const [columns, setColumns] = useState<1 | 2 | 3>(article?.columns || 1);
  const [visuals, setVisuals] = useState<Visual[]>(article?.visuals || []);
  const [useWordCount, setUseWordCount] = useState(true);
  const [lineHeight, setLineHeight] = useState<LineHeight>(article?.lineHeight || '1/50');

  useEffect(() => {
    if (useWordCount) {
      const words = parseInt(wordCount) || 0;
      const wordsPerPage = calculateWordsPerPage(lineHeight, columns, 100);
      const pagesForWords = Math.max(1, Math.ceil(words / wordsPerPage));
      const pagesForVisuals = calculateRequiredPages(visuals);
      const calculatedPages = Math.max(pagesForWords, pagesForVisuals);
      setPageCount(calculatedPages.toString());
    }
  }, [wordCount, useWordCount, lineHeight, columns, visuals]);

  useEffect(() => {
    // Update page count when visuals change
    if (!useWordCount) {
      const pagesForVisuals = calculateRequiredPages(visuals);
      const currentPages = parseInt(pageCount) || 1;
      if (pagesForVisuals > currentPages) {
        setPageCount(pagesForVisuals.toString());
      }
    }
  }, [visuals, useWordCount, pageCount]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const totalPages = parseInt(pageCount) || 1;
    const wordsPerPage = calculateWordsPerPage(lineHeight, columns, 100);
    
    // Ensure visuals have valid page numbers
    const updatedVisuals = visuals.map(visual => ({
      ...visual,
      page: Math.min(Math.max(1, visual.page || 1), totalPages),
      spaceOccupied: (ratioToPercent(visual.width) * ratioToPercent(visual.height)) / 100
    }));

    onAdd({
      title,
      tags,
      url,
      wordCount: useWordCount ? (parseInt(wordCount) || 0) : 0,
      pageCount: totalPages,
      visuals: updatedVisuals,
      columns,
      wordsPerPage,
      lineHeight,
      isLocked: false,
      pages: []
    });
  };

  const handleRandomArticleByType = (type: 'regular' | 'cover' | 'full-page') => {
    const random = generateRandomArticle(availableTags, type);
    setTitle(random.title);
    setTags(random.tags);
    setWordCount(random.wordCount.toString());
    setColumns(random.columns);
    setLineHeight(random.lineHeight);
    setVisuals(random.visuals.map(v => ({ ...v, id: Math.random().toString(36).substr(2, 9) })));
    setUseWordCount(true);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <BasicInfo
        title={title}
        tags={tags}
        url={url}
        onTitleChange={setTitle}
        onUrlChange={setUrl}
        onTagsChange={setTags}
        isEditing={!!article}
      />

      <ContentLength
        useWordCount={useWordCount}
        wordCount={wordCount}
        pageCount={pageCount}
        lineHeight={lineHeight}
        columns={columns}
        onUseWordCountChange={setUseWordCount}
        onWordCountChange={setWordCount}
        onPageCountChange={setPageCount}
        onLineHeightChange={setLineHeight}
        onColumnsChange={setColumns}
      />

      <Visuals
        visuals={visuals}
        pageCount={parseInt(pageCount)}
        onAdd={() => {
          setVisuals([
            ...visuals,
            {
              id: Math.random().toString(36).substr(2, 9),
              title: '',
              type: 'image',
              width: '1/2',
              height: '1/3',
              x: 0,
              y: 0,
              page: 1,
              spaceOccupied: 0
            }
          ]);
        }}
        onUpdate={(index, field, value) => {
          const newVisuals = [...visuals];
          newVisuals[index] = { ...newVisuals[index], [field]: value };
          setVisuals(newVisuals);
        }}
        onRemove={(index) => {
          setVisuals(visuals.filter((_, i) => i !== index));
        }}
      />
      
      <div className="flex justify-end space-x-3">
        {article && onDelete && (
          <button
            type="button"
            onClick={() => onDelete(article.id)}
            className="inline-flex items-center px-4 py-2 border border-red-300 shadow-sm text-sm font-medium rounded-md text-red-700 bg-white hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
          >
            <Trash2 className="w-4 h-4 mr-2" />
            Delete Article
          </button>
        )}
        <Dropdown
          options={[
            {
              label: 'Regular Article',
              onClick: () => handleRandomArticleByType('regular')
            },
            {
              label: 'Cover Page',
              onClick: () => handleRandomArticleByType('cover')
            },
            {
              label: 'Full Page Image',
              onClick: () => handleRandomArticleByType('full-page')
            }
          ]}
          buttonContent={
            <div className="flex">
              <button
                type="button"
                onClick={() => handleRandomArticleByType('regular')}
                className="inline-flex items-center px-4 py-2 border border-r-0 border-gray-300 shadow-sm text-sm font-medium rounded-l-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                <Wand2 className="w-4 h-4 mr-2" />
                Random Article
              </button>
              <button
                type="button"
                className="inline-flex items-center px-2 py-2 border border-l-0 border-gray-300 shadow-sm text-sm font-medium rounded-r-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                <svg className="h-5 w-5 transform rotate-180" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
                </svg>
              </button>
            </div>
          }
        />
        <button
          type="submit"
          className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
        >
          <PlusCircle className="w-4 h-4 mr-2" />
          {article ? 'Update Content' : 'Add Content'}
        </button>
      </div>
    </form>
  );
}

// src/components/ArticleForm/ArticleForm.vue
<script setup lang="ts">
import type { LineHeight, Tag, Visual } from '../../types'
import { PlusCircle, Trash2, Wand2 } from 'lucide-vue-next'
import { computed, ref, watch } from 'vue'
import { useTagStore } from '../../store/tagStore'
import { generateRandomArticle } from '../../utils/articleGenerator'
import { calculateRequiredPages, ratioToPercent } from '../../utils/calculations'
import BasicInfo from './BasicInfo.vue'
import ContentLength from './ContentLength.vue'
import Visuals from './Visuals.vue'

const props = defineProps<{
  article?: any
}>()

const emit = defineEmits<{
  (e: 'add', article: any): void
  (e: 'delete', id: string): void
}>()

// Get tags from the Pinia store
const tagStore = useTagStore()
const availableTags = computed(() => tagStore.tags)

const title = ref(props.article?.title || '')
const url = ref(props.article?.url || '')
const tags = ref<Tag[]>(props.article?.tags || [])
const wordCount = ref(props.article?.wordCount?.toString() || '')
const pageCount = ref(props.article?.pageCount?.toString() || '1')
const columns = ref<1 | 2 | 3>(props.article?.columns || 1)
const visuals = ref<Visual[]>(props.article?.visuals || [])
const useWordCount = ref(true)
const lineHeight = ref<LineHeight>(props.article?.lineHeight || '1/50')

// Watch for changes in wordCount, lineHeight, columns, and visuals
// to update pageCount when using wordCount
watch([wordCount, useWordCount, lineHeight, columns, visuals], () => {
  if (useWordCount.value) {
    const words = Number.parseInt(wordCount.value) || 0
    // Use the same calculation as in ContentLength.vue
    const baseWordsPerPage = 600
    const wordsPerPage = baseWordsPerPage * columns.value
    const pagesForWords = Math.max(1, Math.ceil(words / wordsPerPage))
    const pagesForVisuals = calculateRequiredPages(visuals.value)
    const calculatedPages = Math.max(pagesForWords, pagesForVisuals)
    pageCount.value = calculatedPages.toString()
  }
})

// Watch for changes in visuals to update pageCount when not using wordCount
watch([visuals, useWordCount, pageCount], () => {
  if (!useWordCount.value) {
    const pagesForVisuals = calculateRequiredPages(visuals.value)
    const currentPages = Number.parseInt(pageCount.value) || 1
    if (pagesForVisuals > currentPages) {
      pageCount.value = pagesForVisuals.toString()
    }
  }
})

function handleSubmit(e: Event) {
  e.preventDefault()
  const totalPages = Number.parseInt(pageCount.value) || 1
  // Use the same calculation as in ContentLength.vue
  const baseWordsPerPage = 600
  const wordsPerPage = baseWordsPerPage * columns.value

  // Ensure visuals have valid page numbers
  const updatedVisuals = visuals.value.map(visual => ({
    ...visual,
    page: Math.min(Math.max(1, visual.page || 1), totalPages),
    spaceOccupied: (ratioToPercent(visual.width) * ratioToPercent(visual.height)) / 100,
  }))

  emit('add', {
    title: title.value,
    content: props.article?.content || '',
    tags: tags.value,
    url: url.value,
    wordCount: useWordCount.value ? (Number.parseInt(wordCount.value) || 0) : 0,
    pageCount: totalPages,
    visuals: updatedVisuals,
    columns: columns.value,
    wordsPerPage,
    lineHeight: lineHeight.value,
    isLocked: false,
    pages: [],
  })
}

function handleRandomArticleByType(type: 'regular' | 'cover' | 'full-page') {
  const random = generateRandomArticle(availableTags.value, type)
  title.value = random.title
  tags.value = random.tags
  wordCount.value = random.wordCount.toString()
  columns.value = random.columns
  lineHeight.value = random.lineHeight
  visuals.value = random.visuals.map(v => ({ ...v, id: Math.random().toString(36).substring(2, 9) }))
  useWordCount.value = true
}

function handleTitleChange(newTitle: string) {
  title.value = newTitle
}

function handleUrlChange(newUrl: string) {
  url.value = newUrl
}

function handleTagsChange(newTags: Tag[]) {
  tags.value = newTags
}

function handleUseWordCountChange(value: boolean) {
  useWordCount.value = value
}

function handleWordCountChange(value: string) {
  wordCount.value = value
}

function handlePageCountChange(value: string) {
  pageCount.value = value
}

function handleLineHeightChange(value: LineHeight) {
  lineHeight.value = value
}

function handleColumnsChange(value: 1 | 2 | 3) {
  columns.value = value
}

function handleAddVisual() {
  visuals.value.push({
    id: Math.random().toString(36).substring(2, 9),
    title: '',
    type: 'image',
    width: '1/2',
    height: '1/3',
    x: 0,
    y: 0,
    page: 1,
    spaceOccupied: 0,
    url: '',
  })
}

function handleUpdateVisual(index: number, field: keyof Visual, value: any) {
  const newVisuals = [...visuals.value]
  newVisuals[index] = { ...newVisuals[index], [field]: value }
  visuals.value = newVisuals
}

function handleRemoveVisual(index: number) {
  visuals.value = visuals.value.filter((_, i) => i !== index)
}

function handleDelete() {
  if (props.article?.id) {
    emit('delete', props.article.id)
  }
}
</script>

<template>
  <form class="space-y-6" @submit="handleSubmit">
    <BasicInfo
      :title="title"
      :tags="tags"
      :url="url"
      :is-editing="!!article"
      @title-change="handleTitleChange"
      @url-change="handleUrlChange"
      @tags-change="handleTagsChange"
    />

    <ContentLength
      :use-word-count="useWordCount"
      :word-count="wordCount"
      :page-count="pageCount"
      :line-height="lineHeight"
      :columns="columns"
      @use-word-count-change="handleUseWordCountChange"
      @word-count-change="handleWordCountChange"
      @page-count-change="handlePageCountChange"
      @line-height-change="handleLineHeightChange"
      @columns-change="handleColumnsChange"
    />

    <Visuals
      :visuals="visuals"
      :page-count="parseInt(pageCount)"
      @add="handleAddVisual"
      @update="handleUpdateVisual"
      @remove="handleRemoveVisual"
    />

    <div class="flex justify-end space-x-3">
      <button
        v-if="article && article.id"
        type="button"
        class="inline-flex items-center px-4 py-2 border border-red-300 shadow-xs text-sm font-medium rounded-md text-red-700 bg-white hover:bg-red-50 focus:outline-hidden focus:ring-2 focus:ring-offset-2 focus:ring-red-500"
        @click="handleDelete"
      >
        <Trash2 class="w-4 h-4 mr-2" />
        Delete Article
      </button>

      <div class="relative group">
        <div class="flex">
          <button
            type="button"
            class="inline-flex items-center px-4 py-2 border border-r-0 border-gray-300 shadow-xs text-sm font-medium rounded-l-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-hidden focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            @click="handleRandomArticleByType('regular')"
          >
            <Wand2 class="w-4 h-4 mr-2" />
            Random Article
          </button>
          <button
            type="button"
            class="inline-flex items-center px-2 py-2 border border-l-0 border-gray-300 shadow-xs text-sm font-medium rounded-r-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-hidden focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
          >
            <svg class="h-5 w-5 transform rotate-180" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>

        <!-- Dropdown menu -->
        <div class="absolute bottom-full right-0 mb-2 w-48 transform transition-all duration-200 opacity-0 translate-y-1 invisible group-hover:opacity-100 group-hover:translate-y-0 group-hover:visible">
          <div class="bg-white rounded-md shadow-lg py-1 border border-gray-200">
            <button
              type="button"
              class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
              @click="handleRandomArticleByType('regular')"
            >
              Regular Article
            </button>
            <button
              type="button"
              class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
              @click="handleRandomArticleByType('cover')"
            >
              Cover Page
            </button>
            <button
              type="button"
              class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
              @click="handleRandomArticleByType('full-page')"
            >
              Full Page Image
            </button>
          </div>
          <div class="absolute -bottom-2 right-4 w-4 h-4 transform rotate-45 bg-white border-r border-b border-gray-200" />
        </div>
      </div>

      <button
        type="submit"
        class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-xs text-white bg-blue-600 hover:bg-blue-700 focus:outline-hidden focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
      >
        <PlusCircle class="w-4 h-4 mr-2" />
        {{ article ? 'Update Content' : 'Add Content' }}
      </button>
    </div>
  </form>
</template>
