// src/components/ImagePreview/index.tsx
import React from 'react';

interface ImagePreviewProps {
  src: string;
  alt: string;
  className?: string;
  style?: React.CSSProperties;
}

export function ImagePreview({ src, alt, className = '', style = {} }: ImagePreviewProps) {
  return (
    <div className={`relative overflow-hidden ${className}`} style={style}>
      <img
        src={src}
        alt={alt}
        className="w-full h-full object-cover rounded pointer-events-none"
        draggable={false}
        loading="lazy"
      />
    </div>
  );
}

// src/components/ImagePreview/ImagePreview.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{
  src: string;
  alt: string;
  className?: string;
  style?: Record<string, string>;
}>(), {
  className: '',
  style: () => ({})
});
</script>

<template>
  <div :class="`relative overflow-hidden ${className}`" :style="style">
    <img
      :src="src"
      :alt="alt"
      class="w-full h-full object-cover rounded-sm pointer-events-none"
      :draggable="false"
      loading="lazy"
    />
  </div>
</template>
