// src/pages/FlatPlan.tsx
import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { useSelector, useDispatch } from 'react-redux';
import { MetaTags } from '../components/MetaTags';
import { Modal } from '../components/Modal';
import { HistoryPanel } from '../components/HistoryPanel';
import { DeleteConfirmation } from '../components/DeleteConfirmation';
import { MagazineSettings } from '../components/MagazineSettings';
import { Toolbar } from '../components/Toolbar';
import { MainContent } from '../components/MainContent';
import { CollaborationStatus } from '../components/CollaborationStatus';
import { CursorOverlay } from '../components/CursorOverlay';
import { ArticleForm } from '../components/ArticleForm';
import { Loader } from '../components/Loader';
import type { Article } from '../types';
import type { RootState } from '../store/store';
import { initializeCollaboration, joinSession, getSessionId, isCollaborating, getConnectedPeers } from '../utils/collaboration';
import { addArticle, updateArticle, deleteArticle, setPages, undo, redo, setShowList, setConnectionStatus, syncState } from '../store/magazineSlice';

function LoadingView() {
  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center">
      <Loader />
    </div>
  );
}

export function FlatPlan() {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const { id } = useParams();
  const location = useLocation();
  const { articles, pages, showList, zoomLevel, isShared, allowEdit, isConnecting } = useSelector((state: RootState) => state.magazine);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isHistoryOpen, setIsHistoryOpen] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [showFlipbook, setShowFlipbook] = useState(false);
  const [editingArticle, setEditingArticle] = useState<Article | null>(null);
  const [articleToDelete, setArticleToDelete] = useState<Article | null>(null);
  const [collaborationStatus, setCollaborationStatus] = useState({
    isCollaborating: false,
    peersCount: 0
  });

  useEffect(() => {
    const loadMagazine = async () => {
      if (!id) return;
      setIsLoading(true);
      setLoadError(null);
      
      try {
        const magazines = JSON.parse(localStorage.getItem('magazines') || '[]');
        const magazine = magazines.find((m: any) => m.id === id);
        
        if (!magazine) {
          throw new Error('Magazine not found');
        }

        // Initialize collaboration
        initializeCollaboration();

        // Check URL for collaboration session
        const sessionId = location.state?.session;
        const mode = location.state?.mode;
        
        if (sessionId && mode) {
          console.log('Joining collaboration session:', sessionId);
          dispatch(setConnectionStatus(true));
          await joinSession(sessionId);
          dispatch(setConnectionStatus(false));
        }

        // Initialize magazine state
        dispatch(syncState({
          magazine: magazine.state || {
            articles: [],
            pages: 4,
            pageMargins: {},
            zoomLevel: '2',
            showList: true,
            isShared: false,
            allowEdit: true,
            isConnecting: false,
            history: {
              past: [],
              future: []
            }
          }
        }));

        setIsLoading(false);
      } catch (error) {
        console.error('Error loading magazine:', error);
        setLoadError('Failed to load magazine');
        setIsLoading(false);
      }
    };

    loadMagazine();
  }, [id, dispatch, location.state]);

  useEffect(() => {
    const maxPage = articles.reduce((max, article) => {
      const endPage = article.startPage + article.pageCount - 1;
      return Math.max(max, endPage);
    }, 0);
    
    if (maxPage > pages) {
      dispatch(setPages(maxPage));
    }
  }, [articles, pages, dispatch]);

  useEffect(() => {
    const url = new URL(window.location.href);
    const viewParam = url.searchParams.get('view');
    if (viewParam === 'list' || viewParam === 'grid') {
      dispatch(setShowList(viewParam === 'list'));
    }
  }, [dispatch]);

  useEffect(() => {
    const url = new URL(window.location.href);
    url.searchParams.set('view', showList ? 'list' : 'grid');
    window.history.replaceState({}, '', url.toString());
  }, [showList]);

  useEffect(() => {
    // Update collaboration status periodically
    const interval = setInterval(() => {
      setCollaborationStatus({
        isCollaborating: isCollaborating(),
        peersCount: getConnectedPeers()
      });
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const calculateStartPage = (newArticle: Omit<Article, 'id' | 'startPage'>) => {
    if (articles.length === 0) return 1;
    
    const lastArticle = [...articles].sort((a, b) => {
      const aEndPage = a.startPage + a.pageCount - 1;
      const bEndPage = b.startPage + b.pageCount - 1;
      return bEndPage - aEndPage;
    })[0];

    return lastArticle.startPage + lastArticle.pageCount;
  };

  const handleAddArticle = (newArticle: Omit<Article, 'id' | 'startPage'>) => {
    if (editingArticle) {
      dispatch(updateArticle({
        ...editingArticle,
        ...newArticle,
        id: editingArticle.id,
        startPage: editingArticle.startPage
      }));
      setEditingArticle(null);
    } else {
      const startPage = calculateStartPage(newArticle);
      dispatch(addArticle({
        ...newArticle,
        id: Math.random().toString(36).substr(2, 9),
        startPage,
        isLocked: false
      }));
    }
    setIsModalOpen(false);
  };

  const handleUpdateArticle = (updatedArticle: Article) => {
    dispatch(updateArticle(updatedArticle));
  };

  const handleEditArticle = (article: Article) => {
    setEditingArticle(article);
    setIsModalOpen(true);
  };

  const handleDeleteArticle = (id: string) => {
    const article = articles.find(a => a.id === id);
    if (article) {
      setArticleToDelete(article);
    }
  };

  const confirmDelete = () => {
    if (articleToDelete) {
      dispatch(deleteArticle(articleToDelete.id));
      setArticleToDelete(null);
      setIsModalOpen(false);
    }
  };

  const handleDragEnd = (event: any) => {
    const { active, over } = event;

    if (active.id !== over?.id && over) {
      const oldIndex = articles.findIndex(item => item.id === active.id);
      const newIndex = articles.findIndex(item => item.id === over.id);

      // First pass: Calculate new start pages
      let currentPage = 1;
      const updatedArticles = [...articles];
      const [movedArticle] = updatedArticles.splice(oldIndex, 1);
      updatedArticles.splice(newIndex, 0, movedArticle);

      const reorderedArticles = updatedArticles.map(article => {
        const newArticle = {
          ...article,
          startPage: currentPage
        };
        currentPage += article.pageCount;
        return newArticle;
      });

      // Update all articles in a single batch
      dispatch({
        type: 'magazine/reorderArticles',
        payload: reorderedArticles
      });
    }
  };

  const handleAddPage = () => {
    dispatch(setPages(pages + 1));
  };

  const handleRemovePage = () => {
    if (pages > 1) {
      dispatch(setPages(pages - 1));
      articles.forEach(article => {
        if (article.startPage === pages) {
          dispatch(updateArticle({
            ...article,
            startPage: pages - 1
          }));
        }
      });
    }
  };

  useEffect(() => {
    const handleKeyPress = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'z') {
        e.preventDefault();
        if (e.shiftKey) {
          dispatch(redo());
        } else {
          dispatch(undo());
        }
      } else if ((e.ctrlKey || e.metaKey) && e.key === 'y') {
        e.preventDefault();
        dispatch(redo());
      }
    };

    window.addEventListener('keydown', handleKeyPress);
    return () => window.removeEventListener('keydown', handleKeyPress);
  }, [dispatch]);

  if (isConnecting || isLoading) {
    return <LoadingView />;
  }

  if (loadError) {
    return (
      <div className="min-h-screen bg-gray-100 flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600 mb-4">{loadError}</p>
          <button
            onClick={() => navigate('/magazines')}
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-md"
          >
            Back to Magazines
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 bg-gray-100 py-8 px-4 sm:px-6 lg:px-8">
      <MetaTags 
        title="FlatMag Editor"
        description="Create and manage your magazine layouts with our intuitive drag-and-drop editor. Collaborate with your team in real-time."
      />
      <div className="max-w-7xl mx-auto">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <h2 className="text-2xl font-semibold text-gray-900">Magazine Layout</h2>
            <CollaborationStatus 
              isCollaborating={collaborationStatus.isCollaborating}
              peersCount={collaborationStatus.peersCount}
              isEditingAllowed={allowEdit}
            />
          </div>
          <Toolbar
            showList={showList}
            onHistoryClick={() => setIsHistoryOpen(!isHistoryOpen)}
            onSettingsClick={() => setIsSettingsOpen(true)}
            onFlipbookClick={() => setShowFlipbook(true)}
            onViewToggle={() => dispatch(setShowList(!showList))}
          />
        </div>

        <MainContent
          showList={showList}
          showFlipbook={showFlipbook}
          articles={articles}
          pages={pages}
          zoomLevel={zoomLevel}
          onAddPage={handleAddPage}
          onRemovePage={handleRemovePage}
          onEditArticle={handleEditArticle}
          onUpdateArticle={handleUpdateArticle}
          onDeleteArticle={handleDeleteArticle}
          isEditingAllowed={!isShared || allowEdit}
          onDragEnd={handleDragEnd}
          onFlipbookClose={() => setShowFlipbook(false)}
        />

        <button
          onClick={() => {
            setEditingArticle(null);
            setIsModalOpen(true);
          }}
          disabled={isShared && !allowEdit}
          className="fixed bottom-8 right-8 w-14 h-14 bg-blue-600 rounded-full flex items-center justify-center text-white shadow-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 add-article-button disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
          </svg>
        </button>

        <Modal isOpen={isModalOpen} onClose={() => {
          setIsModalOpen(false);
          setEditingArticle(null);
        }}>
          <ArticleForm 
            onAdd={handleAddArticle} 
            onDelete={handleDeleteArticle}
            article={editingArticle} 
          />
        </Modal>

        <HistoryPanel
          isOpen={isHistoryOpen}
          onClose={() => setIsHistoryOpen(false)}
        />

        <MagazineSettings
          isOpen={isSettingsOpen}
          onClose={() => setIsSettingsOpen(false)}
        />

        <DeleteConfirmation
          title={articleToDelete?.title || ''}
          isOpen={!!articleToDelete}
          onConfirm={confirmDelete}
          onCancel={() => setArticleToDelete(null)}
        />

        {collaborationStatus.isCollaborating && (
          <CursorOverlay />
        )}
      </div>
    </div>
  );
}

// src/pages/FlatPlan.vue
<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useMagazineStore } from '../store/magazineStore';
import { Plus } from 'lucide-vue-next';
import MetaTags from '../components/MetaTags.vue';
import Modal from '../components/Modal.vue';
import HistoryPanel from '../components/HistoryPanel.vue';
import DeleteConfirmation from '../components/DeleteConfirmation.vue';
import MagazineSettings from '../components/MagazineSettings.vue';
import Toolbar from '../components/Toolbar';
import MainContent from '../components/MainContent';
import CollaborationStatus from '../components/CollaborationStatus.vue';
import CursorOverlay from '../components/CursorOverlay.vue';
import ArticleForm from '../components/ArticleForm/ArticleForm.vue';
import Loader from '../components/Loader.vue';
import { initializeCollaboration, joinSession, isCollaborating, getConnectedPeers } from '../utils/collaboration';

const route = useRoute();
const router = useRouter();
const magazineId = computed(() => route.params.id as string);
const magazineStore = useMagazineStore();

// Initialize default values for store properties
const defaultArticles = ref<any[]>([]);
const defaultPages = ref(4);
let defaultShowList = true;

const isLoading = ref(true);
const loadError = ref<string | null>(null);
const isModalOpen = ref(false);
const isHistoryOpen = ref(false);
const isSettingsOpen = ref(false);
const showFlipbook = ref(false);
const editingArticle = ref<any>(null);
const articleToDelete = ref<any>(null);
const collaborationStatus = ref({
  isCollaborating: false,
  peersCount: 0
});

// Update URL when showList changes
watch(() => magazineStore.showList || defaultShowList, (showList) => {
  const url = new URL(window.location.href);
  url.searchParams.set('view', showList ? 'list' : 'grid');
  window.history.replaceState({}, '', url.toString());
});

// Update collaboration status periodically
onMounted(() => {
  const interval = setInterval(() => {
    collaborationStatus.value = {
      isCollaborating: isCollaborating(),
      peersCount: getConnectedPeers()
    };
  }, 1000);

  return () => clearInterval(interval);
});

onMounted(async () => {
  if (!magazineId.value) return;
  
  isLoading.value = true;
  loadError.value = null;
  
  try {
    // Load magazine data
    const magazines = JSON.parse(localStorage.getItem('magazines') || '[]');
    const magazine = magazines.find((m: any) => m.id === magazineId.value);
    
    if (!magazine) {
      throw new Error('Magazine not found');
    }

    // Initialize collaboration
    initializeCollaboration();

    // Check URL for collaboration session
    const sessionId = route.query.session as string;
    const mode = route.query.mode as string;
    
    if (sessionId && mode) {
      console.log('Joining collaboration session:', sessionId);
      if (typeof magazineStore.setConnectionStatus === 'function') {
        magazineStore.setConnectionStatus(true);
      }
      await joinSession(sessionId);
      if (typeof magazineStore.setConnectionStatus === 'function') {
        magazineStore.setConnectionStatus(false);
      }
    }

    // Initialize magazine state
    if (typeof magazineStore.syncState === 'function') {
      // Get the magazine state or create a default one
      const magazineState = magazine.state || {
        articles: [],
        pages: 4,
        pageMargins: {},
        zoomLevel: '2',
        showList: true,
        isShared: false,
        allowEdit: true,
        isConnecting: false,
        history: {
          past: [],
          future: []
        }
      };
      
      // Ensure title, issueNumber, publicationDate, and pageRatio are set
      magazineState.title = magazine.title || 'My Magazine';
      magazineState.issueNumber = magazine.issue_number || 1;
      magazineState.publicationDate = magazine.publication_date || new Date().toISOString();
      magazineState.pageRatio = magazine.page_ratio || '1/1.4142';
      
      // Sync the state to the store
      magazineStore.syncState({
        magazine: magazineState
      });
    }

    isLoading.value = false;
  } catch (error) {
    console.error('Error loading magazine:', error);
    loadError.value = 'Failed to load magazine';
    isLoading.value = false;
  }
});

// Watch for articles that exceed the current page count
watch(() => magazineStore.articles || defaultArticles.value, (articles) => {
  if (!articles || articles.length === 0) return;
  
  const maxPage = articles.reduce((max, article) => {
    if (!article.startPage || !article.pageCount) return max;
    const endPage = article.startPage + article.pageCount - 1;
    return Math.max(max, endPage);
  }, 0);
  
  if (maxPage > (magazineStore.pages || defaultPages.value)) {
    if (typeof magazineStore.setPages === 'function') {
      magazineStore.setPages(maxPage);
    } else {
      defaultPages.value = maxPage;
    }
  }
}, { deep: true });

// Check URL for view parameter
onMounted(() => {
  const url = new URL(window.location.href);
  const viewParam = url.searchParams.get('view');
  if (viewParam === 'list' || viewParam === 'grid') {
    if (typeof magazineStore.setShowList === 'function') {
      magazineStore.setShowList(viewParam === 'list');
    } else {
      defaultShowList = viewParam === 'list';
    }
  }
});

const calculateStartPage = (newArticle: any) => {
  const articles = magazineStore.articles || defaultArticles.value;
  if (!articles || articles.length === 0) return 1;
  
  const lastArticle = [...articles].sort((a, b) => {
    if (!a.startPage || !a.pageCount || !b.startPage || !b.pageCount) return 0;
    const aEndPage = a.startPage + a.pageCount - 1;
    const bEndPage = b.startPage + b.pageCount - 1;
    return bEndPage - aEndPage;
  })[0];

  if (!lastArticle.startPage || !lastArticle.pageCount) return 1;
  return lastArticle.startPage + lastArticle.pageCount;
};

const handleAddArticle = (newArticle: any) => {
  if (editingArticle.value) {
    if (typeof magazineStore.updateArticle === 'function') {
      magazineStore.updateArticle({
        ...editingArticle.value,
        ...newArticle,
        id: editingArticle.value.id,
        startPage: editingArticle.value.startPage
      });
    }
    editingArticle.value = null;
  } else {
    const startPage = calculateStartPage(newArticle);
    if (typeof magazineStore.addArticle === 'function') {
      // Ensure content property is present
      const articleToAdd = {
        ...newArticle,
        id: Math.random().toString(36).substr(2, 9),
        startPage,
        isLocked: false,
        content: newArticle.content || ''
      };
      
      magazineStore.addArticle(articleToAdd);
    }
  }
  isModalOpen.value = false;
};

const handleUpdateArticle = (updatedArticle: any) => {
  if (typeof magazineStore.updateArticle === 'function') {
    magazineStore.updateArticle(updatedArticle);
  }
};

const handleEditArticle = (article: any) => {
  editingArticle.value = article;
  isModalOpen.value = true;
};

const handleDeleteArticle = (id: string) => {
  const articles = magazineStore.articles || defaultArticles.value;
  const article = articles.find((a: any) => a.id === id);
  if (article) {
    articleToDelete.value = article;
  }
};

const confirmDelete = () => {
  if (articleToDelete.value && typeof magazineStore.deleteArticle === 'function') {
    magazineStore.deleteArticle(articleToDelete.value.id);
    articleToDelete.value = null;
  }
};

const handleDragEnd = (event: any) => {
  const { active, over } = event;
  const articles = magazineStore.articles || defaultArticles.value;

  if (active.id !== over?.id && over && articles) {
    const oldIndex = articles.findIndex((item: any) => item.id === active.id);
    const newIndex = articles.findIndex((item: any) => item.id === over.id);

    // First pass: Calculate new start pages
    let currentPage = 1;
    const updatedArticles = [...articles];
    const [movedArticle] = updatedArticles.splice(oldIndex, 1);
    updatedArticles.splice(newIndex, 0, movedArticle);

    const reorderedArticles = updatedArticles.map((article: any) => {
      const newArticle = {
        ...article,
        startPage: currentPage
      };
      if (article.pageCount) {
        currentPage += article.pageCount;
      } else {
        currentPage += 1;
      }
      return newArticle;
    });

    // Update all articles in a single batch
    if (typeof magazineStore.reorderArticles === 'function') {
      magazineStore.reorderArticles(reorderedArticles);
    } else {
      // This is a fallback that won't be used in practice
      console.log('reorderArticles not available');
    }
  }
};

const handleAddPage = () => {
  const currentPages = magazineStore.pages || defaultPages.value;
  if (typeof magazineStore.setPages === 'function') {
    magazineStore.setPages(currentPages + 1);
  } else {
    defaultPages.value = currentPages + 1;
  }
};

const handleRemovePage = () => {
  const currentPages = magazineStore.pages || defaultPages.value;
  if (currentPages > 1) {
    if (typeof magazineStore.setPages === 'function') {
      magazineStore.setPages(currentPages - 1);
    } else {
      defaultPages.value = currentPages - 1;
    }
    
    const articles = magazineStore.articles || defaultArticles.value;
    if (articles) {
      articles.forEach((article: any) => {
        if (article.startPage === currentPages) {
          if (typeof magazineStore.updateArticle === 'function') {
            magazineStore.updateArticle({
              ...article,
              startPage: currentPages - 1
            });
          }
        }
      });
    }
  }
};
</script>

<template>
  <div class="flex-1 px-4 py-8 bg-gray-100 sm:px-6 lg:px-8">
    <MetaTags 
      title="Magazine Flat Plan - FlatMag" 
      description="Plan and organize your magazine layout." 
    />
    
    <div v-if="isLoading || magazineStore.isConnecting" class="flex items-center justify-center min-h-screen bg-gray-100">
      <Loader />
    </div>
    
    <div v-else-if="loadError" class="flex items-center justify-center min-h-screen bg-gray-100">
      <div class="w-full max-w-md p-8 space-y-6 text-center bg-white shadow-lg rounded-xl">
        <div class="flex justify-center">
          <div class="w-16 h-16 text-red-600">⚠️</div>
        </div>
        <div class="space-y-2">
          <h2 class="text-2xl font-bold text-gray-900">Error Loading Magazine</h2>
          <p class="text-gray-600">{{ loadError }}</p>
        </div>
        <div class="flex justify-center">
          <button
            @click="router.push('/magazines')"
            class="px-4 py-2 text-white transition-colors bg-blue-600 rounded-lg hover:bg-blue-700"
          >
            Back to Magazines
          </button>
        </div>
      </div>
    </div>
    
    <div v-else class="mx-auto max-w-7xl">
      <div class="flex items-center justify-between">
        <div class="flex items-center space-x-4">
          <h2 class="text-2xl font-semibold text-gray-900">Magazine Layout</h2>
          <CollaborationStatus 
            :isCollaborating="collaborationStatus.isCollaborating"
            :peersCount="collaborationStatus.peersCount"
            :isEditingAllowed="magazineStore.allowEdit"
          />
        </div>
        <Toolbar
          :showList="magazineStore.showList"
          @history-click="isHistoryOpen = !isHistoryOpen"
          @settings-click="isSettingsOpen = true"
          @flipbook-click="showFlipbook = true"
          @view-toggle="typeof magazineStore.setShowList === 'function' ? 
            magazineStore.setShowList(!magazineStore.showList) : 
            (defaultShowList = !defaultShowList)"
        />
      </div>

      <MainContent
        :showList="magazineStore.showList"
        :showFlipbook="showFlipbook"
        :articles="magazineStore.articles"
        :pages="magazineStore.pages"
        :zoomLevel="magazineStore.zoomLevel"
        :isEditingAllowed="!magazineStore.isShared || magazineStore.allowEdit"
        @add-page="handleAddPage"
        @remove-page="handleRemovePage"
        @edit-article="handleEditArticle"
        @update-article="handleUpdateArticle"
        @delete-article="handleDeleteArticle"
        @drag-end="handleDragEnd"
        @flipbook-close="showFlipbook = false"
      />

      <button
        @click="() => { editingArticle = null; isModalOpen = true; }"
        :disabled="magazineStore.isShared && !magazineStore.allowEdit"
        class="fixed flex items-center justify-center text-white bg-blue-600 rounded-full shadow-lg bottom-8 right-8 w-14 h-14 hover:bg-blue-700 focus:outline-hidden focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 add-article-button disabled:opacity-50 disabled:cursor-not-allowed"
      >
        <Plus class="w-6 h-6" />
      </button>

      <Modal :isOpen="isModalOpen" @close="() => { isModalOpen = false; editingArticle = null; }">
        <ArticleForm 
          @add="handleAddArticle" 
          @delete="handleDeleteArticle"
          :article="editingArticle" 
        />
      </Modal>

      <HistoryPanel
        :isOpen="isHistoryOpen"
        @close="isHistoryOpen = false"
      />

      <MagazineSettings
        :isOpen="isSettingsOpen"
        @close="isSettingsOpen = false"
      />

      <DeleteConfirmation
        :title="articleToDelete?.title || ''"
        :isOpen="!!articleToDelete"
        @confirm="confirmDelete"
        @cancel="articleToDelete = null"
      />

      <CursorOverlay v-if="collaborationStatus.isCollaborating" />
    </div>
  </div>
</template>
