// src/components/DraggableVisual.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';
import { getImageUrl } from '../utils/imageHandler';
import type { Visual, SizeRatio, Article } from '../types';
import { useMagazineStore } from '../store/magazineStore';

interface ImageLoadingState {
  isLoading: boolean;
  error: string | null;
  retryCount: number;
}

const props = defineProps<{
  visual: Visual;
  isLocked: boolean;
  currentPage: number;
  article: Article;
}>();

const emit = defineEmits<{
  (e: 'updateArticle', article: Article): void;
}>();

const magazineStore = useMagazineStore();
const loadingState = ref<ImageLoadingState>({
  isLoading: false,
  error: null,
  retryCount: 0
});

const imageUrl = ref<string | null>(null);
const isDragDisabled = computed(() => props.isLocked);

// Create refs for draggable functionality
const nodeRef = ref<HTMLElement | null>(null);
const transform = ref({ x: 0, y: 0 });

// Create attributes and listeners for draggable
const attributes = {
  role: 'button',
  'aria-roledescription': 'draggable',
  tabIndex: 0
};

const listeners = {
  onPointerDown: (e: PointerEvent) => {
    if (isDragDisabled.value) return;
    // Handle pointer down event
    // This would normally be handled by the DnD library
  }
};

// Function to set the node ref
const setNodeRef = (element: HTMLElement | null) => {
  nodeRef.value = element;
};

// Watch for URL changes to load images
watch(() => props.visual.url, (newUrl) => {
  if (newUrl) {
    loadImage(newUrl);
  }
}, { immediate: true });

// Load image with retry logic
const loadImage = async (url: string) => {
  if (!url) return;
  
  loadingState.value.isLoading = true;
  loadingState.value.error = null;
  
  try {
    const imageUrl = await getImageUrl(url);
    if (imageUrl) {
      loadingState.value.isLoading = false;
      loadingState.value.retryCount = 0;
    } else {
      throw new Error('Failed to load image');
    }
  } catch (error) {
    loadingState.value.isLoading = false;
    loadingState.value.error = error instanceof Error ? error.message : 'Unknown error';
    
    // Retry logic
    if (loadingState.value.retryCount < 3) {
      loadingState.value.retryCount++;
      setTimeout(() => loadImage(url), 1000 * loadingState.value.retryCount);
    }
  }
};

// Convert size ratio to percentage
const sizeToPercent = (size: SizeRatio): number => {
  switch (size) {
    case 'full': return 100;
    case '1/2': return 50;
    case '1/3': return 33.33;
    case '1/4': return 25;
    case '1/6': return 16.67;
    case '1/8': return 12.5;
    case '1/10': return 10;
    default: return 50;
  }
};

// Computed styles for the visual
const visualStyle = computed(() => {
  const width = sizeToPercent(props.visual.width as SizeRatio);
  const height = sizeToPercent(props.visual.height as SizeRatio);
  
  return {
    width: `${width}%`,
    height: `${height}%`,
    left: `${props.visual.x}%`,
    top: `${props.visual.y}%`,
    transform: transform.value ? `translate3d(${transform.value.x}px, ${transform.value.y}px, 0)` : undefined,
    cursor: isDragDisabled.value ? 'default' : 'grab',
    zIndex: props.visual.width === 'full' && props.visual.height === 'full' ? 0 : 1
  };
});
</script>

<template>
  <div
    ref="setNodeRef"
    :style="visualStyle"
    class="absolute rounded-sm overflow-hidden"
    v-bind="attributes"
    v-on="listeners"
  >
    <img
      v-if="visual.type === 'image' && visual.url"
      :src="visual.url"
      :alt="visual.title || 'Visual'"
      class="w-full h-full object-cover"
      draggable="false"
    />
    <div
      v-else-if="visual.type === 'illustration'"
      class="w-full h-full bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center"
    >
      <span class="text-gray-500">Illustration</span>
    </div>
    <div
      v-else
      class="w-full h-full bg-gray-200 flex items-center justify-center"
    >
      <span class="text-gray-500">{{ visual.title || 'No media' }}</span>
    </div>
  </div>
</template>

// src/components/DraggableVisual.tsx
import React, { useEffect, useState } from 'react';
import { useDraggable } from '@dnd-kit/core';
import { getImageUrl } from '../utils/imageHandler';
import type { Visual, SizeRatio, Article } from '../types';
import { useSelector } from 'react-redux';
import type { RootState } from '../store/store';
import type { ImageLoadingState } from '../utils/imageHandler/types';

interface DraggableVisualProps {
  visual: Visual;
  isLocked: boolean;
  currentPage: number;
  article: Article;
  onUpdateArticle: (article: Article) => void;
}

const ratioToPercent = (ratio: SizeRatio): number => {
  if (ratio === 'full') return 100;
  const [num, den] = ratio.split('/').map(Number);
  return (num / den) * 100;
};

export function DraggableVisual({ 
  visual, 
  isLocked, 
  currentPage,
  article,
  onUpdateArticle
}: DraggableVisualProps) {
  const [loadingState, setLoadingState] = useState<ImageLoadingState>({
    isLoading: false,
    error: null,
    retryCount: 0
  });
  const showList = useSelector((state: RootState) => state.magazine.showList);
  
  const isFullSize = visual.width === 'full' && visual.height === 'full';
  const isDragDisabled = isLocked || (!showList && isFullSize);

  const loadImage = async () => {
    if (!visual.url || visual.url.startsWith('data:')) return;
    
    setLoadingState(prev => ({
      ...prev,
      isLoading: true,
      error: null
    }));
    
    try {
      const url = await getImageUrl(visual.url);
      onUpdateArticle({
        ...article,
        visuals: article.visuals.map(v =>
          v.id === visual.id ? { ...v, url } : v
        )
      });
    } catch (error) {
      console.error('Error loading image:', error);
      setLoadingState(prev => ({
        ...prev,
        error: 'Failed to load image',
        retryCount: prev.retryCount + 1
      }));
    } finally {
      setLoadingState(prev => ({
        ...prev,
        isLoading: false
      }));
    }
  };

  const { attributes, listeners, setNodeRef, transform } = useDraggable({
    id: visual.id,
    disabled: isDragDisabled,
    data: {
      currentPage,
      type: 'visual'
    }
  });

  useEffect(() => {
    if (!visual.url?.startsWith('data:')) {
      setLoadingState({
        isLoading: false,
        error: null,
        retryCount: 0
      });
      loadImage();
    }
  }, [visual.url]);


  // Only show the visual if it's on the current page
  if (visual.page !== currentPage) {
    return null;
  }

  const style = transform ? {
    transform: `translate3d(${transform.x}px, ${transform.y}px, 0)`,
  } : undefined;

  const width = ratioToPercent(visual.width);
  const height = ratioToPercent(visual.height);

  return (
    <div
      ref={setNodeRef}
      {...attributes}
      {...listeners}
      className={`absolute select-none ${isDragDisabled ? '' : 'cursor-move'}`}
      style={{
        left: `${visual.x}%`,
        top: `${visual.y}%`,
        width: width === 100 ? '100%' : `${width}%`,
        height: height === 100 ? '100%' : 'auto',
        zIndex: 10,
        ...style,
        userSelect: 'none',
        WebkitUserSelect: 'none',
        touchAction: 'none'
      }}
    >
      <div
        className={`${
          visual.type === 'illustration'
            ? 'bg-gray-100 border-2 border-dashed border-gray-300'
            : visual.url ? '' : 'bg-gray-200'
        } rounded flex flex-col items-center justify-center overflow-hidden h-full`}
        style={{
          height: height === 100 ? '100%' : `${Math.max(height * 2, 80)}px`,
          pointerEvents: 'none'
        }}
      >
        {loadingState.isLoading ? (
          <div className="text-gray-500 text-sm text-center p-2">
            <div className="animate-pulse flex flex-col items-center">
              <div className="h-8 w-8 mb-2 rounded-full bg-gray-200"></div>
              <span className="block">Loading image...</span>
            </div>
          </div>
        ) : loadingState.error ? (
          <div className="text-red-500 text-sm text-center p-2 space-y-1">
            <span className="block">Error loading image</span>
            <span className="block text-xs">{loadingState.error}</span>
            {loadingState.retryCount < 3 && (
              <span className="block text-xs text-gray-500">
                Retrying... ({loadingState.retryCount + 1}/3)
              </span>
            )}
          </div>
        ) : visual.url ? (
          <img 
            src={visual.url} 
            alt={visual.title || 'Visual content'}
            className="w-full h-full object-cover rounded pointer-events-none"
            loading="lazy"
            draggable={false}
            style={{ maxWidth: '100%', maxHeight: '100%' }}
            onError={(e) => {
              console.error('Image load error:', e);
              const target = e.target as HTMLImageElement;
              setLoadingState(prev => ({
                ...prev,
                error: `Failed to display image: ${target.src}`
              }));
            }}
          />
        ) : (
          <>
            <span className="text-gray-500 text-sm pointer-events-none">
              {visual.type.charAt(0).toUpperCase() + visual.type.slice(1)}
            </span>
            {visual.title && (
              <span className="text-xs text-gray-400 mt-1 pointer-events-none">
                {visual.title}
              </span>
            )}
          </>
        )}
      </div>
    </div>
  );
}
