// src/components/Navbar.vue
<script setup lang="ts">
import { computed } from 'vue';
import { RouterLink, useRoute } from 'vue-router';
import { Layout } from 'lucide-vue-next';
import { getSessionId, getConnectedUsers } from '../utils/collaboration';
import UserPresence from './UserPresence.vue';

const route = useRoute();
const isHome = computed(() => route.path === '/');
const isEditor = computed(() => route.path.startsWith('/flat-plan'));
const isMagazines = computed(() => route.path === '/magazines');
const currentUserId = getSessionId();
const connectedUsers = getConnectedUsers();
</script>

<template>
  <nav :class="`${isHome ? 'absolute w-full z-50' : 'bg-white shadow-xs'} py-4 mb-0`">
    <div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
      <div class="flex items-center justify-between space-x-4">
        <RouterLink to="/" class="flex items-center space-x-3">
          <Layout :class="`w-8 h-8 ${isHome ? 'text-white' : 'text-blue-600'}`" />
          <span :class="`text-xl font-bold ${isHome ? 'text-white' : 'text-gray-900'}`">
            FlatMag
          </span>
        </RouterLink>
        
        <UserPresence 
          v-if="!isHome" 
          :users="connectedUsers" 
          :currentUserId="currentUserId" 
        />
        
        <div v-if="!isHome" class="flex items-center space-x-4">
          <RouterLink
            v-if="isEditor"
            to="/magazines"
            class="text-gray-600 hover:text-gray-900"
          >
            Back to Magazines
          </RouterLink>
          
          <RouterLink
            v-if="isMagazines"
            to="/"
            class="text-gray-600 hover:text-gray-900"
          >
            Back to Home
          </RouterLink>
        </div>
      </div>
    </div>
  </nav>
</template>

// src/components/Navbar.tsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Layout } from 'lucide-react';
import { UserPresence } from './UserPresence';
import { getSessionId, getConnectedUsers } from '../utils/collaboration';

export function Navbar() {
  const location = useLocation();
  const isHome = location.pathname === '/';
  const isEditor = location.pathname.startsWith('/flat-plan');
  const isMagazines = location.pathname === '/magazines';
  const currentUserId = getSessionId();
  const connectedUsers = getConnectedUsers();

  return (
    <nav className={`${isHome ? 'absolute w-full z-50' : 'bg-white shadow-sm'} py-4 mb-0`}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center space-x-4">
          <Link to="/" className="flex items-center space-x-3">
            <Layout className={`w-8 h-8 ${isHome ? 'text-white' : 'text-blue-600'}`} />
            <span className={`text-xl font-bold ${isHome ? 'text-white' : 'text-gray-900'}`}>
              FlatMag
            </span>
          </Link>
          {!isHome && (
            <UserPresence users={connectedUsers} currentUserId={currentUserId} />
          )}
          {!isHome && (
            <div className="flex items-center space-x-4">
              {isEditor && (
                <Link
                  to="/magazines"
                  className="text-gray-600 hover:text-gray-900"
                >
                  Back to Magazines
                </Link>
              )}
              {isMagazines && (
                <Link
                  to="/"
                  className="text-gray-600 hover:text-gray-900"
                >
                  Back to Home
                </Link>
              )}
            </div>
          )}
        </div>
      </div>
    </nav>
  );
}
