// src/components/WaitingRoom.vue
<script setup lang="ts">
import { Layout, Loader, AlertTriangle } from 'lucide-vue-next';
import { useRouter } from 'vue-router';

const router = useRouter();

defineProps<{
  status: 'connecting' | 'waiting' | 'syncing' | 'error';
  error?: string;
}>();

const reloadPage = () => {
  window.location.reload();
};

const goToMagazines = () => {
  router.push('/magazines');
};
</script>

<template>
  <div class="min-h-screen bg-gray-100 flex items-center justify-center">
    <div class="bg-white p-8 rounded-xl shadow-lg max-w-md w-full text-center space-y-6">
      <template v-if="status === 'error'">
        <div class="flex justify-center">
          <AlertTriangle class="w-16 h-16 text-red-600" />
        </div>
        <div class="space-y-2">
          <h2 class="text-2xl font-bold text-gray-900">Connection Error</h2>
          <p class="text-gray-600">{{ error }}</p>
        </div>
        <div class="flex flex-col space-y-3">
          <button
            @click="reloadPage"
            class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            Try Again
          </button>
          <button
            @click="goToMagazines"
            class="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
          >
            Back to Magazines
          </button>
        </div>
      </template>
      <template v-else>
        <div class="flex justify-center">
          <Layout class="w-16 h-16 text-blue-600" />
        </div>
        <div class="space-y-2">
          <h2 class="text-2xl font-bold text-gray-900">
            <template v-if="status === 'connecting'">Connecting to Session</template>
            <template v-else-if="status === 'waiting'">Waiting for Host</template>
            <template v-else-if="status === 'syncing'">Loading Magazine</template>
          </h2>
          <p class="text-gray-600">
            <template v-if="status === 'connecting'">Establishing connection...</template>
            <template v-else-if="status === 'waiting'">Waiting for host to accept...</template>
            <template v-else-if="status === 'syncing'">Syncing magazine data...</template>
          </p>
        </div>
        <div class="flex justify-center">
          <Loader class="w-8 h-8 text-blue-600 animate-spin" />
        </div>
      </template>
    </div>
  </div>
</template>

// src/components/WaitingRoom.tsx
import React from 'react';
import { Layout, Loader, AlertTriangle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

interface WaitingRoomProps {
  status: 'connecting' | 'waiting' | 'syncing' | 'error';
  error?: string;
}

export function WaitingRoom({ status, error }: WaitingRoomProps) {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center">
      <div className="bg-white p-8 rounded-xl shadow-lg max-w-md w-full text-center space-y-6">
        {status === 'error' ? (
          <>
            <div className="flex justify-center">
              <AlertTriangle className="w-16 h-16 text-red-600" />
            </div>
            <div className="space-y-2">
              <h2 className="text-2xl font-bold text-gray-900">Connection Error</h2>
              <p className="text-gray-600">{error}</p>
            </div>
            <div className="flex flex-col space-y-3">
              <button
                onClick={() => window.location.reload()}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
              >
                Try Again
              </button>
              <button
                onClick={() => navigate('/magazines')}
                className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
              >
                Back to Magazines
              </button>
            </div>
          </>
        ) : (
          <>
            <div className="flex justify-center">
              <Layout className="w-16 h-16 text-blue-600" />
            </div>
            <div className="space-y-2">
              <h2 className="text-2xl font-bold text-gray-900">
                {status === 'connecting' && 'Connecting to Session'}
                {status === 'waiting' && 'Waiting for Host'}
                {status === 'syncing' && 'Loading Magazine'}
              </h2>
              <p className="text-gray-600">
                {status === 'connecting' && 'Establishing connection...'}
                {status === 'waiting' && 'Waiting for host to accept...'}
                {status === 'syncing' && 'Syncing magazine data...'}
              </p>
            </div>
            <div className="flex justify-center">
              <Loader className="w-8 h-8 text-blue-600 animate-spin" />
            </div>
          </>
        )}
      </div>
    </div>
  );
}
